"""Phase 8 remote identity, enrollment, and request-authentication boundary."""

from jarvis.remote.browser import (
    BrowserOriginError,
    BrowserOriginPolicy,
    FixedWindowRateLimiter,
    RateLimitDecision,
)
from jarvis.remote.models import (
    BrowserSessionCredential,
    DeviceRecord,
    DeviceState,
    DeviceType,
    EnrollmentCompletion,
    EnrollmentTicket,
    KeyRotationRequest,
    RemoteAuditEvent,
    RemoteAuditOutcome,
    RemoteIdentityContext,
    RemoteScope,
    RemoteSessionKind,
    SessionCredential,
    SessionRequest,
)
from jarvis.remote.pwa import (
    MAX_PWA_EVENT_BYTES,
    MAX_PWA_EVENTS_PER_SUBSCRIPTION,
    MAX_PWA_RETAINED_EVENT_BYTES,
    MAX_PWA_SUBSCRIPTIONS,
    MAX_PWA_SUBSCRIPTIONS_PER_SESSION,
    PWAEvent,
    PWAEventHub,
    PWAEventPage,
    PWAEventTopic,
    PWASubscription,
    PWATransportError,
)
from jarvis.remote.service import (
    RemoteAuthenticationError,
    RemoteIdentityService,
    RemoteStateError,
)
from jarvis.remote.signing import (
    REQUEST_AUDIENCE,
    SIGNATURE_HEADERS,
    SignedRequest,
    build_enrollment_proof,
    build_rotation_proof,
    canonical_request,
    encode_base64url,
)
from jarvis.remote.sqlite_store import SQLiteRemoteIdentityStore

__all__ = [
    "MAX_PWA_EVENTS_PER_SUBSCRIPTION",
    "MAX_PWA_EVENT_BYTES",
    "MAX_PWA_RETAINED_EVENT_BYTES",
    "MAX_PWA_SUBSCRIPTIONS",
    "MAX_PWA_SUBSCRIPTIONS_PER_SESSION",
    "REQUEST_AUDIENCE",
    "SIGNATURE_HEADERS",
    "BrowserOriginError",
    "BrowserOriginPolicy",
    "BrowserSessionCredential",
    "DeviceRecord",
    "DeviceState",
    "DeviceType",
    "EnrollmentCompletion",
    "EnrollmentTicket",
    "FixedWindowRateLimiter",
    "KeyRotationRequest",
    "PWAEvent",
    "PWAEventHub",
    "PWAEventPage",
    "PWAEventTopic",
    "PWASubscription",
    "PWATransportError",
    "RateLimitDecision",
    "RemoteAuditEvent",
    "RemoteAuditOutcome",
    "RemoteAuthenticationError",
    "RemoteIdentityContext",
    "RemoteIdentityService",
    "RemoteScope",
    "RemoteSessionKind",
    "RemoteStateError",
    "SQLiteRemoteIdentityStore",
    "SessionCredential",
    "SessionRequest",
    "SignedRequest",
    "build_enrollment_proof",
    "build_rotation_proof",
    "canonical_request",
    "encode_base64url",
]
