const API="/api/v1";
const DB_NAME="jarvis-private-client";
const STORE="identity";
const SCOPES=["browser.session","identity.read","events.read","session.revoke","client.chat","client.tasks.read","client.status.read"];
const encoder=new TextEncoder();
const state={csrf:null,subscription:null,cursor:0,conversation:null,online:false,stopping:false,streamAbort:null,hasIdentity:false};
const ui={connection:document.querySelector("#connection"),setup:document.querySelector("#setup"),ticket:document.querySelector("#ticket"),enroll:document.querySelector("#enroll"),connect:document.querySelector("#connect"),notify:document.querySelector("#notify"),logout:document.querySelector("#logout"),chat:document.querySelector("#chat"),message:document.querySelector("#message"),send:document.querySelector("#send"),log:document.querySelector("#log"),tasks:document.querySelector("#tasks"),refreshTasks:document.querySelector("#refresh-tasks"),device:document.querySelector("#device-status"),notice:document.querySelector("#notice")};

function b64url(bytes){return btoa(String.fromCharCode(...new Uint8Array(bytes))).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");}
function randomId(prefix){return `${prefix}:${crypto.randomUUID()}`;}
function proof(profile,...values){let text=`${profile}\n`;for(const value of values){const bytes=encoder.encode(String(value));text+=`${bytes.length}:${value}\n`;}return encoder.encode(text);}
async function digest(value){return b64url(await crypto.subtle.digest("SHA-256",value));}
function timestamp(){return new Date().toISOString().replace(/\.(\d{3})Z$/,".$1000Z");}
async function canonical({method,path,query="",body,identity,date,nonce}){
  const bodyDigest=await digest(body),components=[["@method",method.toUpperCase()],["@authority",location.host.toLowerCase()],["@path",path],["@query",query],["content-digest",`sha-256=:${bodyDigest}:`],["x-jarvis-date",date],["x-jarvis-nonce",nonce],["x-jarvis-audience","jarvis-api"],["x-jarvis-device",identity.deviceId],["x-jarvis-key-version",String(identity.keyVersion)],["authorization-digest","-"]];
  let text="jarvis-http-signature-v1\n";for(const [name,value] of components)text+=`${name}:${encoder.encode(value).length}:${value}\n`;return encoder.encode(text);
}
async function signedHeaders(identity,method,path,body){const date=timestamp(),nonce=b64url(crypto.getRandomValues(new Uint8Array(16))),signature=b64url(await crypto.subtle.sign("Ed25519",identity.privateKey,await canonical({method,path,body,identity,date,nonce})));return {"Content-Type":"application/json","X-Jarvis-Audience":"jarvis-api","X-Jarvis-Date":date,"X-Jarvis-Device":identity.deviceId,"X-Jarvis-Key-Version":String(identity.keyVersion),"X-Jarvis-Nonce":nonce,"X-Jarvis-Signature":signature};}
function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function dbAction(mode,operation){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,mode),store=tx.objectStore(STORE);let request;try{request=operation(store);}catch(error){db.close();reject(error);return;}request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close();tx.onerror=()=>reject(tx.error);});}
const loadIdentity=()=>dbAction("readonly",store=>store.get("device"));
const saveIdentity=value=>dbAction("readwrite",store=>store.put(value,"device"));
const clearIdentity=()=>dbAction("readwrite",store=>store.clear());
class ApiError extends Error{constructor(message,status){super(message);this.status=status;}}
async function api(path,options={}){const headers={...(options.headers||{})},method=options.method||"GET";if(method==="GET")headers["X-Jarvis-Browser-Origin"]=window.location.origin;if(method!=="GET"&&state.csrf)headers["X-Jarvis-CSRF"]=state.csrf;const response=await fetch(`${API}${path}`,{credentials:"include",cache:"no-store",...options,headers});if(response.status===401){setConnected(false,"Session expired");throw new ApiError("Session expired",401);}if(!response.ok){let detail=`HTTP ${response.status}`;try{detail=(await response.json()).detail||detail;}catch{}throw new ApiError(detail,response.status);}return response;}
function setConnected(value,label=value?"Connected":"Offline shell"){state.online=value&&navigator.onLine;ui.connection.textContent=navigator.onLine?label:"Network offline";ui.connection.className=`status ${state.online?"online":navigator.onLine?"warn":""}`;for(const element of [ui.message,ui.send,ui.notify,ui.refreshTasks])element.disabled=!state.online;ui.logout.disabled=!state.hasIdentity;}
function announce(message){ui.notice.textContent=message;ui.notice.classList.add("visible");setTimeout(()=>ui.notice.classList.remove("visible"),3500);}
function row(kind,text,requestId){let target=requestId?ui.log.querySelector(`[data-request="${CSS.escape(requestId)}"]`):null;if(!target){target=document.createElement("div");target.className=`entry ${kind}`;if(requestId)target.dataset.request=requestId;ui.log.append(target);}target.textContent=text;ui.log.scrollTop=ui.log.scrollHeight;return target;}

async function enroll(){if(!crypto.subtle||!window.indexedDB)throw new Error("Secure browser cryptography unavailable");const ticket=JSON.parse(ui.ticket.value);for(const key of ["id","challenge"]){if(typeof ticket[key]!=="string")throw new Error("Enrollment ticket is incomplete");}const pair=await crypto.subtle.generateKey("Ed25519",false,["sign","verify"]),publicKey=b64url(await crypto.subtle.exportKey("raw",pair.publicKey)),proofSignature=b64url(await crypto.subtle.sign("Ed25519",pair.privateKey,proof("jarvis-enrollment-v1",ticket.id,ticket.challenge,publicKey,"1")));const response=await fetch(`${API}/enrollments/complete`,{method:"POST",credentials:"omit",cache:"no-store",headers:{"Content-Type":"application/json"},body:JSON.stringify({enrollment_id:ticket.id,challenge:ticket.challenge,public_key:publicKey,proof_signature:proofSignature,protocol_version:"1"})});if(!response.ok)throw new Error("Enrollment rejected");const device=await response.json();await saveIdentity({privateKey:pair.privateKey,deviceId:device.id,keyVersion:device.key_version});state.hasIdentity=true;ui.ticket.value="";await connect();}
async function createSubscription(){const subscription=await (await api("/client/subscriptions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topics:["chat","tasks","device"]})})).json();state.subscription=subscription.id;state.cursor=subscription.next_cursor;sessionStorage.setItem("jarvis-subscription",state.subscription);sessionStorage.setItem("jarvis-cursor",String(state.cursor));}
async function resetSubscription(){const previous=state.subscription;if(previous){try{await api(`/client/subscriptions/${encodeURIComponent(previous)}`,{method:"DELETE"});}catch{}}await createSubscription();}
async function connect(){const identity=await loadIdentity();if(!identity)throw new Error("No enrolled device key in this browser");state.hasIdentity=true;const path="/browser/sessions",body=encoder.encode(JSON.stringify({requested_scopes:SCOPES,audience:"jarvis-api"})),headers=await signedHeaders(identity,"POST",`${API}${path}`,body),response=await fetch(`${API}${path}`,{method:"POST",credentials:"include",cache:"no-store",headers,body});if(!response.ok)throw new Error(`Session bootstrap rejected (${response.status})`);const credential=await response.json();state.csrf=credential.csrf_token;await createSubscription();setConnected(true);await refreshStatus();await refreshTasks();startStreamOwnership();}
async function refreshStatus(){const status=await (await api("/client/status")).json();ui.device.replaceChildren();const entries=[["Name",status.device.display_name],["State",status.device.state],["Key version",status.device.key_version],["Session",status.session.id]];for(const [name,value] of entries){const wrap=document.createElement("div"),dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=name;dd.textContent=String(value);wrap.append(dt,dd);ui.device.append(wrap);}}
async function refreshTasks(){const tasks=await (await api("/client/tasks?limit=50")).json();ui.tasks.replaceChildren();if(!tasks.length){const item=document.createElement("li");item.textContent="No tasks.";ui.tasks.append(item);return;}for(const task of tasks){const item=document.createElement("li");item.textContent=`${task.id} — ${task.status}`;ui.tasks.append(item);}}
function processEvent(event){if(!Number.isInteger(event.cursor)||event.cursor<1)throw new Error("Invalid event cursor");if(event.cursor<=state.cursor)return;if(event.cursor!==state.cursor+1)throw new Error("Event cursor gap");state.cursor=event.cursor;sessionStorage.setItem("jarvis-cursor",String(state.cursor));if(event.topic==="chat"){const id=event.request_id;if(event.event_type==="chat.started")row("jarvis","JARVIS: …",id);if(event.event_type==="chat.delta")row("jarvis",`${ui.log.querySelector(`[data-request="${CSS.escape(id)}"]`)?.textContent||"JARVIS: "}${event.payload.content_delta||""}`,id);if(event.event_type==="chat.frame"&&event.payload.type==="assistant_delta")row("jarvis",`${ui.log.querySelector(`[data-request="${CSS.escape(id)}"]`)?.textContent||"JARVIS: "}${event.payload.content_delta||""}`,id);if(event.event_type==="chat.completed"){state.conversation=event.payload.conversation_id||state.conversation;notifyGeneric();}if(event.event_type==="chat.failed")row("meta","Request failed safely.",id);}if(event.topic==="tasks")refreshTasks().catch(()=>{});}
function parseSse(text){for(const block of text.split("\n\n")){const line=block.split("\n").find(item=>item.startsWith("data: "));if(line)processEvent(JSON.parse(line.slice(6)));}}
async function streamLoop(){while(state.online&&!state.stopping&&state.subscription){state.streamAbort=new AbortController();try{const query=new URLSearchParams({subscription_id:state.subscription,after:String(state.cursor),limit:"100",wait:"20"}),response=await api(`/client/events?${query}`,{signal:state.streamAbort.signal});parseSse(await response.text());}catch(error){if(state.stopping||error.name==="AbortError")break;if(error.status===401||error.status===403){state.stopping=true;setConnected(false,"Sign in again");announce(error.message);break;}if((error.status===404||error.status===409)&&state.csrf){try{await resetSubscription();announce("Stream restarted from current durable state");continue;}catch{}}setConnected(false,"Reconnecting");await new Promise(resolve=>setTimeout(resolve,Math.min(5000,500+Math.random()*1500)));if(navigator.onLine)setConnected(true,"Reconnecting");}}}
async function startStreamOwnership(){state.stopping=false;if(navigator.locks){navigator.locks.request("jarvis-pwa-stream",{ifAvailable:true},async lock=>{if(!lock){announce("Another tab owns live stream");return;}await streamLoop();});}else{announce("Single-tab stream ownership unavailable");await streamLoop();}}
async function sendMessage(event){event.preventDefault();if(!state.online||!state.subscription)return;const message=ui.message.value.trim();if(!message)return;const requestId=randomId("request");row("user",`You: ${message}`);ui.message.value="";try{const response=await api("/client/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({request_id:requestId,subscription_id:state.subscription,message,conversation_id:state.conversation})});const result=await response.json();state.conversation=result.conversation_id||state.conversation;if(response.status!==202&&!ui.log.querySelector(`[data-request="${CSS.escape(requestId)}"]`))row("jarvis",`JARVIS: ${result.reply||"Completed"}`,requestId);}catch(error){row("meta",`Request failed: ${error.message}`,requestId);}}
async function enableNotifications(){if(!("Notification" in window))throw new Error("Notifications unsupported");const permission=await Notification.requestPermission();if(permission!=="granted")throw new Error("Notification permission denied");sessionStorage.setItem("jarvis-notifications","enabled");ui.notify.textContent="Notifications enabled";announce("Notifications contain generic text only");}
function notifyGeneric(){if(sessionStorage.getItem("jarvis-notifications")==="enabled"&&document.hidden&&Notification.permission==="granted")new Notification("JARVIS",{body:"JARVIS has an update.",tag:"jarvis-update",renotify:false,silent:true});}
async function logout(){state.stopping=true;state.streamAbort?.abort();try{if(state.csrf)await api("/sessions/current",{method:"DELETE"});}catch{}state.csrf=null;state.subscription=null;state.cursor=0;state.conversation=null;state.hasIdentity=false;for(const key of ["jarvis-subscription","jarvis-cursor","jarvis-notifications"])sessionStorage.removeItem(key);await clearIdentity();for(const registration of await navigator.serviceWorker?.getRegistrations?.()||[]){registration.active?.postMessage("JARVIS_LOGOUT");await registration.unregister();}for(const key of await caches.keys())if(key.startsWith("jarvis-shell-"))await caches.delete(key);setConnected(false,"Logged out — device key erased");ui.log.replaceChildren();announce("Local credential, cursors, notifications, and shell cache erased");}
async function guarded(action){try{await action();}catch(error){announce(error.message||"Operation failed safely");}}

ui.enroll.addEventListener("click",()=>guarded(enroll));ui.connect.addEventListener("click",()=>guarded(connect));ui.chat.addEventListener("submit",sendMessage);ui.notify.addEventListener("click",()=>guarded(enableNotifications));ui.logout.addEventListener("click",()=>guarded(logout));ui.refreshTasks.addEventListener("click",()=>guarded(refreshTasks));
window.addEventListener("offline",()=>setConnected(false,"Network offline"));window.addEventListener("online",()=>{setConnected(Boolean(state.csrf),state.csrf?"Reconnecting":"Online — sign in");});
if("serviceWorker" in navigator)navigator.serviceWorker.register("/app/sw.js?v=3",{scope:"/app/"}).catch(()=>announce("Offline shell unavailable"));
loadIdentity().then(identity=>{state.hasIdentity=Boolean(identity);ui.logout.disabled=!state.hasIdentity;if(identity)announce("Enrolled key found. Connect to start a fresh session.");}).catch(()=>announce("Device storage unavailable"));
