const API="/api/v1";
const DB_NAME="jarvis-private-client";
const STORE="identity";
const SCOPES=["browser.session","identity.read","events.read","session.revoke","client.chat","client.tasks.read","client.status.read"];
const HEALTH_SCOPE="client.health.read";
const encoder=new TextEncoder();
const state={csrf:null,subscription:null,cursor:0,conversation:null,online:false,stopping:false,streamAbort:null,hasIdentity:false,sessionGeneration:0,logoutPending:null,bootstrap:null,identityWrite:null,healthAllowed:false,healthGeneration:0,healthAbort:null};
const ui={connection:document.querySelector("#connection"),setup:document.querySelector("#setup"),ticket:document.querySelector("#ticket"),enroll:document.querySelector("#enroll"),connect:document.querySelector("#connect"),notify:document.querySelector("#notify"),logout:document.querySelector("#logout"),chat:document.querySelector("#chat"),message:document.querySelector("#message"),send:document.querySelector("#send"),log:document.querySelector("#log"),tasks:document.querySelector("#tasks"),refreshTasks:document.querySelector("#refresh-tasks"),device:document.querySelector("#device-status"),notice:document.querySelector("#notice"),refreshGarmin:document.querySelector("#refresh-garmin"),garminState:document.querySelector("#garmin-state"),garminMetrics:document.querySelector("#garmin-metrics"),garminActivities:document.querySelector("#garmin-activities")};

function renderGarmin(summary){ui.garminMetrics.replaceChildren();const values=[["Steps",summary.steps],["Resting heart rate",summary.resting_heart_rate==null?null:`${summary.resting_heart_rate} bpm`],["Sleep",summary.sleep_minutes==null?null:`${Math.floor(summary.sleep_minutes/60)}h ${summary.sleep_minutes%60}m`],["Stress",summary.stress],["Body Battery",summary.body_battery]];for(const [label,value] of values){const card=document.createElement("div"),dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=label;dd.textContent=value==null?"Unavailable":String(value);card.append(dt,dd);ui.garminMetrics.append(card);}ui.garminActivities.replaceChildren();for(const activity of summary.activities||[]){const item=document.createElement("li");item.textContent=`${activity.name} · ${activity.type}${activity.started?` · ${activity.started.slice(0,10)}`:""}`;ui.garminActivities.append(item);}if(!ui.garminActivities.children.length){const item=document.createElement("li");item.textContent="No recent activities.";ui.garminActivities.append(item);}const refreshed=Date.parse(summary.refreshed_at),age=Date.now()-refreshed,stale=!Number.isFinite(refreshed)||age<0||age>=300000,checked=Number.isFinite(refreshed)?new Date(refreshed).toLocaleString():"Unknown";ui.garminState.textContent=`${summary.date} · last checked ${checked}${stale?" · Stale. Refresh Garmin to check current data.":""}`;}
function cancelGarmin(){state.healthGeneration+=1;state.healthAbort?.abort();state.healthAbort=null;}
function clearGarmin(){cancelGarmin();state.healthAllowed=false;ui.refreshGarmin.disabled=true;ui.garminMetrics.replaceChildren();ui.garminActivities.replaceChildren();ui.garminState.textContent="Connect JARVIS to see Garmin data.";}
async function refreshGarmin(force){if(!state.online||!state.healthAllowed)return;cancelGarmin();const generation=state.healthGeneration,csrf=state.csrf,controller=new AbortController();state.healthAbort=controller;const current=()=>generation===state.healthGeneration&&state.csrf===csrf&&state.online&&state.healthAllowed&&!controller.signal.aborted;ui.garminState.textContent="Checking Garmin…";try{const summary=await (await api(`/client/garmin${force?"?refresh=true":""}`,{signal:controller.signal})).json();if(current())renderGarmin(summary);}catch(error){if(current()&&error.name!=="AbortError"){const message=error.status===503?"Garmin unavailable. Connect Garmin on the trusted laptop, then refresh.":"Garmin check failed. Try again after connection recovers.";ui.garminState.textContent=message+(ui.garminMetrics.children.length?" Shown Garmin data may be stale.":"");}}finally{if(state.healthAbort===controller)state.healthAbort=null;}}
ui.refreshGarmin.addEventListener("click",()=>refreshGarmin(true));
function b64url(bytes){return btoa(String.fromCharCode(...new Uint8Array(bytes))).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");}
function randomId(prefix){return `${prefix}:${crypto.randomUUID()}`;}
function proof(profile,...values){let text=`${profile}\n`;for(const value of values){const bytes=encoder.encode(String(value));text+=`${bytes.length}:${value}\n`;}return encoder.encode(text);}
async function digest(value){return b64url(await crypto.subtle.digest("SHA-256",value));}
function timestamp(){return new Date().toISOString().replace(/\.(\d{3})Z$/,".$1000Z");}
async function canonical({method,path,query="",body,identity,date,nonce}){
  const bodyDigest=await digest(body),components=[["@method",method.toUpperCase()],["@authority",location.host.toLowerCase()],["@path",path],["@query",query],["content-digest",`sha-256=:${bodyDigest}:`],["x-jarvis-date",date],["x-jarvis-nonce",nonce],["x-jarvis-audience","jarvis-api"],["x-jarvis-device",identity.deviceId],["x-jarvis-key-version",String(identity.keyVersion)],["authorization-digest","-"]];
  let text="jarvis-http-signature-v1\n";for(const [name,value] of components)text+=`${name}:${encoder.encode(value).length}:${value}\n`;return encoder.encode(text);
}
async function signedHeaders(identity,method,path,body){const date=timestamp(),nonce=b64url(crypto.getRandomValues(new Uint8Array(16))),signature=b64url(await crypto.subtle.sign("Ed25519",identity.privateKey,await canonical({method,path,body,identity,date,nonce})));return {"Content-Type":"application/json","X-Jarvis-Audience":"jarvis-api","X-Jarvis-Date":date,"X-Jarvis-Device":identity.deviceId,"X-Jarvis-Key-Version":String(identity.keyVersion),"X-Jarvis-Nonce":nonce,"X-Jarvis-Signature":signature};}
function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function dbAction(mode,operation){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,mode),store=tx.objectStore(STORE);let request;try{request=operation(store);}catch(error){db.close();reject(error);return;}request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close();tx.onerror=()=>reject(tx.error);});}
const loadIdentity=()=>dbAction("readonly",store=>store.get("device"));
const saveIdentity=value=>dbAction("readwrite",store=>store.put(value,"device"));
const clearIdentity=()=>dbAction("readwrite",store=>store.clear());
class ApiError extends Error{constructor(message,status){super(message);this.status=status;}}
function currentSession(generation,csrf){return state.sessionGeneration===generation&&state.csrf===csrf;}
function revokeRemoteSession(csrf){const controller=new AbortController();return new Promise(resolve=>{let settled=false;const finish=()=>{if(settled)return;settled=true;clearTimeout(timer);resolve();},timer=setTimeout(()=>{controller.abort();finish();},5000);fetch(`${API}/sessions/current`,{method:"DELETE",credentials:"include",cache:"no-store",headers:{"X-Jarvis-CSRF":csrf},signal:controller.signal}).then(finish,finish);});}
function startBootstrap(headers,body){const controller=new AbortController(),bootstrap={controller,headersReceived:false,promise:null};let timer;const request=(async()=>{const response=await fetch(`${API}/browser/sessions`,{method:"POST",credentials:"include",cache:"no-store",headers,body,signal:controller.signal});bootstrap.headersReceived=true;if(!response.ok)throw new Error(`Session bootstrap rejected (${response.status})`);return response.json();})();bootstrap.promise=Promise.race([request,new Promise((resolve,reject)=>{timer=setTimeout(()=>{controller.abort();reject(new Error("Session bootstrap timed out"));},5000);})]).finally(()=>clearTimeout(timer));return bootstrap;}
async function api(path,options={}){const headers={...(options.headers||{})},method=options.method||"GET",csrf=state.csrf,generation=state.sessionGeneration;if(method==="GET")headers["X-Jarvis-Browser-Origin"]=window.location.origin;if(method!=="GET"&&state.csrf)headers["X-Jarvis-CSRF"]=state.csrf;const response=await fetch(`${API}${path}`,{credentials:"include",cache:"no-store",...options,headers});if(options.signal?.aborted)throw new DOMException("Request aborted","AbortError");if(response.status===401){if(currentSession(generation,csrf)){clearGarmin();setConnected(false,"Session expired");}throw new ApiError("Session expired",401);}if(!response.ok){let detail=`HTTP ${response.status}`;try{detail=(await response.json()).detail||detail;}catch{}throw new ApiError(detail,response.status);}return response;}
function setConnected(value,label=value?"Connected":"Offline shell"){state.online=value&&navigator.onLine;ui.connection.textContent=navigator.onLine?label:"Network offline";ui.connection.className=`status ${state.online?"online":navigator.onLine?"warn":""}`;for(const element of [ui.message,ui.send,ui.notify,ui.refreshTasks])element.disabled=!state.online;ui.refreshGarmin.disabled=!state.online||!state.healthAllowed;ui.logout.disabled=!state.hasIdentity;if(!state.online){cancelGarmin();if(state.healthAllowed)ui.garminState.textContent="Offline. Shown Garmin data may be stale.";}}
function announce(message){ui.notice.textContent=message;ui.notice.classList.add("visible");setTimeout(()=>ui.notice.classList.remove("visible"),3500);}
function row(kind,text,requestId){let target=requestId?ui.log.querySelector(`[data-request="${CSS.escape(requestId)}"]`):null;if(!target){target=document.createElement("div");target.className=`entry ${kind}`;if(requestId)target.dataset.request=requestId;ui.log.append(target);}target.textContent=text;ui.log.scrollTop=ui.log.scrollHeight;return target;}

async function enroll(){if(state.hasIdentity)throw new Error("Log out and erase this device before re-enrollment");const generation=++state.sessionGeneration,current=()=>state.sessionGeneration===generation;if(state.logoutPending)await state.logoutPending;if(!current())return;if(!crypto.subtle||!window.indexedDB)throw new Error("Secure browser cryptography unavailable");const existing=await loadIdentity();if(!current())return;if(existing)throw new Error("Log out and erase this device before re-enrollment");const ticket=JSON.parse(ui.ticket.value);for(const key of ["id","challenge"]){if(typeof ticket[key]!=="string")throw new Error("Enrollment ticket is incomplete");}const pair=await crypto.subtle.generateKey("Ed25519",false,["sign","verify"]),publicKey=b64url(await crypto.subtle.exportKey("raw",pair.publicKey)),proofSignature=b64url(await crypto.subtle.sign("Ed25519",pair.privateKey,proof("jarvis-enrollment-v1",ticket.id,ticket.challenge,publicKey,"1")));if(!current())return;const response=await fetch(`${API}/enrollments/complete`,{method:"POST",credentials:"omit",cache:"no-store",headers:{"Content-Type":"application/json"},body:JSON.stringify({enrollment_id:ticket.id,challenge:ticket.challenge,public_key:publicKey,proof_signature:proofSignature,protocol_version:"1"})});if(!current())return;if(!response.ok)throw new Error("Enrollment rejected");const device=await response.json();if(!current())return;const write=saveIdentity({privateKey:pair.privateKey,deviceId:device.id,keyVersion:device.key_version,healthAllowed:Array.isArray(ticket.approved_scopes)&&ticket.approved_scopes.includes(HEALTH_SCOPE)});state.identityWrite=write;try{await write;}finally{if(state.identityWrite===write)state.identityWrite=null;}if(!current())return;state.hasIdentity=true;ui.ticket.value="";await connect();}
async function createSubscription(){const generation=state.sessionGeneration,csrf=state.csrf,subscription=await (await api("/client/subscriptions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topics:["chat","tasks","device"]})})).json();if(!currentSession(generation,csrf))return;state.subscription=subscription.id;state.cursor=subscription.next_cursor;sessionStorage.setItem("jarvis-subscription",state.subscription);sessionStorage.setItem("jarvis-cursor",String(state.cursor));}
async function resetSubscription(){const generation=state.sessionGeneration,csrf=state.csrf,previous=state.subscription;if(previous){try{await api(`/client/subscriptions/${encodeURIComponent(previous)}`,{method:"DELETE"});}catch{}}if(currentSession(generation,csrf))await createSubscription();}
async function connect(){const generation=++state.sessionGeneration,current=()=>state.sessionGeneration===generation;clearGarmin();state.streamAbort?.abort();setConnected(false,"Connecting");if(state.logoutPending)await state.logoutPending;if(!current())return;const previous=state.bootstrap;if(previous){if(!previous.headersReceived)previous.controller.abort();try{await previous.promise;}catch{}if(!current())return;}const identity=await loadIdentity();if(!current())return;if(!identity)throw new Error("No enrolled device key in this browser");state.hasIdentity=true;const path="/browser/sessions",requestedScopes=identity.healthAllowed?[...SCOPES,HEALTH_SCOPE]:SCOPES,body=encoder.encode(JSON.stringify({requested_scopes:requestedScopes,audience:"jarvis-api"})),headers=await signedHeaders(identity,"POST",`${API}${path}`,body);if(!current())return;const bootstrap=startBootstrap(headers,body);state.bootstrap=bootstrap;let credential;try{credential=await bootstrap.promise;}catch(error){if(current()){setConnected(false,"Connection failed");if(error.name!=="AbortError")throw error;}return;}finally{if(state.bootstrap===bootstrap)state.bootstrap=null;}if(!current())return;state.csrf=credential.csrf_token;state.healthAllowed=Boolean(identity.healthAllowed);await createSubscription();if(!current())return;setConnected(true);await refreshStatus();if(!current())return;await refreshTasks();if(!current())return;if(state.healthAllowed)refreshGarmin(false).catch(()=>{});else ui.garminState.textContent="Garmin access needs a new approved browser enrollment.";startStreamOwnership();}
async function refreshStatus(){const generation=state.sessionGeneration,csrf=state.csrf,status=await (await api("/client/status")).json();if(!currentSession(generation,csrf))return;ui.device.replaceChildren();const entries=[["Name",status.device.display_name],["State",status.device.state],["Key version",status.device.key_version],["Session",status.session.id]];for(const [name,value] of entries){const wrap=document.createElement("div"),dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=name;dd.textContent=String(value);wrap.append(dt,dd);ui.device.append(wrap);}}
async function refreshTasks(){const generation=state.sessionGeneration,csrf=state.csrf,tasks=await (await api("/client/tasks?limit=50")).json();if(!currentSession(generation,csrf))return;ui.tasks.replaceChildren();if(!tasks.length){const item=document.createElement("li");item.textContent="No tasks.";ui.tasks.append(item);return;}for(const task of tasks){const item=document.createElement("li");item.textContent=`${task.id} — ${task.status}`;ui.tasks.append(item);}}
function processEvent(event){if(!Number.isInteger(event.cursor)||event.cursor<1)throw new Error("Invalid event cursor");if(event.cursor<=state.cursor)return;if(event.cursor!==state.cursor+1)throw new Error("Event cursor gap");state.cursor=event.cursor;sessionStorage.setItem("jarvis-cursor",String(state.cursor));if(event.topic==="chat"){const id=event.request_id;if(event.event_type==="chat.started")row("jarvis","JARVIS: …",id);if(event.event_type==="chat.delta")row("jarvis",`${ui.log.querySelector(`[data-request="${CSS.escape(id)}"]`)?.textContent||"JARVIS: "}${event.payload.content_delta||""}`,id);if(event.event_type==="chat.frame"&&event.payload.type==="assistant_delta")row("jarvis",`${ui.log.querySelector(`[data-request="${CSS.escape(id)}"]`)?.textContent||"JARVIS: "}${event.payload.content_delta||""}`,id);if(event.event_type==="chat.completed"){state.conversation=event.payload.conversation_id||state.conversation;notifyGeneric();}if(event.event_type==="chat.failed")row("meta","Request failed safely.",id);}if(event.topic==="tasks")refreshTasks().catch(()=>{});}
function parseSse(text){for(const block of text.split("\n\n")){const line=block.split("\n").find(item=>item.startsWith("data: "));if(line)processEvent(JSON.parse(line.slice(6)));}}
async function streamLoop(){const generation=state.sessionGeneration,csrf=state.csrf,current=()=>currentSession(generation,csrf)&&!state.stopping;while(state.online&&current()&&state.subscription){state.streamAbort=new AbortController();try{const query=new URLSearchParams({subscription_id:state.subscription,after:String(state.cursor),limit:"100",wait:"20"}),response=await api(`/client/events?${query}`,{signal:state.streamAbort.signal}),text=await response.text();if(!current())break;parseSse(text);}catch(error){if(!current()||error.name==="AbortError")break;if(error.status===401||error.status===403){state.stopping=true;setConnected(false,"Sign in again");announce(error.message);break;}if((error.status===404||error.status===409)&&state.csrf){try{await resetSubscription();if(!current())break;announce("Stream restarted from current durable state");continue;}catch{}}if(!current())break;setConnected(false,"Reconnecting");await new Promise(resolve=>setTimeout(resolve,Math.min(5000,500+Math.random()*1500)));if(!current())break;if(navigator.onLine)setConnected(true,"Reconnecting");}}}
async function startStreamOwnership(){state.stopping=false;if(navigator.locks){navigator.locks.request("jarvis-pwa-stream",{ifAvailable:true},async lock=>{if(!lock){announce("Another tab owns live stream");return;}await streamLoop();});}else{announce("Single-tab stream ownership unavailable");await streamLoop();}}
async function sendMessage(event){event.preventDefault();if(!state.online||!state.subscription)return;const generation=state.sessionGeneration,csrf=state.csrf,message=ui.message.value.trim();if(!message)return;const requestId=randomId("request");row("user",`You: ${message}`);ui.message.value="";try{const response=await api("/client/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({request_id:requestId,subscription_id:state.subscription,message,conversation_id:state.conversation})});const result=await response.json();if(!currentSession(generation,csrf))return;state.conversation=result.conversation_id||state.conversation;if(response.status!==202&&!ui.log.querySelector(`[data-request="${CSS.escape(requestId)}"]`))row("jarvis",`JARVIS: ${result.reply||"Completed"}`,requestId);}catch(error){if(currentSession(generation,csrf))row("meta",`Request failed: ${error.message}`,requestId);}}
async function enableNotifications(){const generation=state.sessionGeneration,csrf=state.csrf;if(!("Notification" in window))throw new Error("Notifications unsupported");const permission=await Notification.requestPermission();if(!currentSession(generation,csrf))return;if(permission!=="granted")throw new Error("Notification permission denied");sessionStorage.setItem("jarvis-notifications","enabled");ui.notify.textContent="Notifications enabled";announce("Notifications contain generic text only");}
function notifyGeneric(){if(sessionStorage.getItem("jarvis-notifications")==="enabled"&&document.hidden&&Notification.permission==="granted")new Notification("JARVIS",{body:"JARVIS has an update.",tag:"jarvis-update",renotify:false,silent:true});}
async function logout(){const csrf=state.csrf,generation=++state.sessionGeneration,bootstrap=state.bootstrap,write=state.identityWrite,previous=state.logoutPending;clearGarmin();state.stopping=true;state.streamAbort?.abort();if(bootstrap&&!bootstrap.headersReceived)bootstrap.controller.abort();state.csrf=null;state.subscription=null;state.cursor=0;state.conversation=null;state.hasIdentity=false;ui.device.replaceChildren();ui.tasks.replaceChildren();ui.log.replaceChildren();ui.message.value="";ui.ticket.value="";setConnected(false,"Logging out");for(const key of ["jarvis-subscription","jarvis-cursor","jarvis-notifications"])sessionStorage.removeItem(key);const remote=csrf?revokeRemoteSession(csrf):Promise.resolve(),bootstrapCleanup=bootstrap?bootstrap.promise.then(credential=>revokeRemoteSession(credential.csrf_token),()=>{}):Promise.resolve(),local=(async()=>{if(write){try{await write;}catch{}}await clearIdentity();for(const registration of await navigator.serviceWorker?.getRegistrations?.()||[]){registration.active?.postMessage("JARVIS_LOGOUT");await registration.unregister();}for(const key of await caches.keys())if(key.startsWith("jarvis-shell-"))await caches.delete(key);if(state.sessionGeneration===generation){setConnected(false,"Logged out — device key erased");announce("Local credential, cursors, notifications, and shell cache erased");}})(),pending=Promise.allSettled([previous,remote,bootstrapCleanup,local]);state.logoutPending=pending;pending.then(()=>{if(state.logoutPending===pending)state.logoutPending=null;});await local;}
async function guarded(action){try{await action();}catch(error){announce(error.message||"Operation failed safely");}}

ui.enroll.addEventListener("click",()=>guarded(enroll));ui.connect.addEventListener("click",()=>guarded(connect));ui.chat.addEventListener("submit",sendMessage);ui.notify.addEventListener("click",()=>guarded(enableNotifications));ui.logout.addEventListener("click",()=>guarded(logout));ui.refreshTasks.addEventListener("click",()=>guarded(refreshTasks));
window.addEventListener("offline",()=>setConnected(false,"Network offline"));window.addEventListener("online",()=>{setConnected(Boolean(state.csrf),state.csrf?"Reconnecting":"Online — sign in");});
if("serviceWorker" in navigator)navigator.serviceWorker.register("/app/sw.js?v=6",{scope:"/app/"}).catch(()=>announce("Offline shell unavailable"));
const initialGeneration=state.sessionGeneration;
loadIdentity().then(identity=>{if(state.sessionGeneration!==initialGeneration)return;state.hasIdentity=Boolean(identity);ui.logout.disabled=!state.hasIdentity;if(identity)announce("Enrolled key found. Connect to start a fresh session.");}).catch(()=>{if(state.sessionGeneration===initialGeneration)announce("Device storage unavailable");});
