"""Phase 3 permission, approval, canonicalization, and audit contracts."""

from .canonical import canonical_json, canonical_json_bytes, canonicalize, sha256_fingerprint
from .contracts import (
    ActionAuditStore,
    ActionHandler,
    ActionStateStore,
    PrivilegeBroker,
    TrustedApprovalSurface,
)
from .models import (
    ActionAuditEvent,
    ActionAuditEventType,
    ActionDefinition,
    ActionEffect,
    ActionPolicyDecision,
    ActorContext,
    ApprovalDecision,
    ApprovalGrant,
    ApprovalRequest,
    AuthenticationAssurance,
    CanonicalAction,
    ExecutionOutcome,
    ExecutionReceipt,
    InteractionInterface,
    PolicyDisposition,
    PostconditionEvidence,
    PostconditionStatus,
    RollbackReceipt,
    RollbackStatus,
)
from .policy import PermissionEngine
from .service import ActionCoordinator, ActionCoordinatorResult, ActionCoordinatorStatus
from .sqlite_store import (
    ActionAuditSequenceConflictError,
    ActionAuditSummary,
    ActionLifecycleEvent,
    ActionLifecycleEventType,
    ActionReceiptSummary,
    ActionStoreConflictError,
    ActionStoreStateError,
    ApprovalRequestRecord,
    ApprovalSource,
    ApprovalStatus,
    ControlIntentEvent,
    ControlIntentOutcome,
    ExpirationResult,
    GrantRecord,
    GrantStatus,
    SQLiteActionStore,
)
from .trusted_cli import LocalCliApprovalSurface, approval_phrase, render_approval_summary

__all__ = [
    "ActionAuditEvent",
    "ActionAuditEventType",
    "ActionAuditSequenceConflictError",
    "ActionAuditStore",
    "ActionAuditSummary",
    "ActionCoordinator",
    "ActionCoordinatorResult",
    "ActionCoordinatorStatus",
    "ActionDefinition",
    "ActionEffect",
    "ActionHandler",
    "ActionLifecycleEvent",
    "ActionLifecycleEventType",
    "ActionPolicyDecision",
    "ActionReceiptSummary",
    "ActionStateStore",
    "ActionStoreConflictError",
    "ActionStoreStateError",
    "ActorContext",
    "ApprovalDecision",
    "ApprovalGrant",
    "ApprovalRequest",
    "ApprovalRequestRecord",
    "ApprovalSource",
    "ApprovalStatus",
    "AuthenticationAssurance",
    "CanonicalAction",
    "ControlIntentEvent",
    "ControlIntentOutcome",
    "ExecutionOutcome",
    "ExecutionReceipt",
    "ExpirationResult",
    "GrantRecord",
    "GrantStatus",
    "InteractionInterface",
    "LocalCliApprovalSurface",
    "PermissionEngine",
    "PolicyDisposition",
    "PostconditionEvidence",
    "PostconditionStatus",
    "PrivilegeBroker",
    "RollbackReceipt",
    "RollbackStatus",
    "SQLiteActionStore",
    "TrustedApprovalSurface",
    "approval_phrase",
    "canonical_json",
    "canonical_json_bytes",
    "canonicalize",
    "render_approval_summary",
    "sha256_fingerprint",
]
