"""Generic wearable contracts and hardware-independent fakes."""

from .contracts import WearableClient
from .fake import FakeWearableClient
from .models import (
    MAX_WEARABLE_DURATION_MS,
    MAX_WEARABLE_EVENTS,
    MAX_WEARABLE_PAYLOAD_BYTES,
    WEARABLE_PROTOCOL_MAJOR,
    WEARABLE_PROTOCOL_MINOR,
    WearableAuthorization,
    WearableCapability,
    WearableCapabilityDescriptor,
    WearableCapabilityLimits,
    WearableConnectionState,
    WearableDataClass,
    WearableDeviceDescriptor,
    WearableError,
    WearableFailureCode,
    WearableNegotiationRequest,
    WearableNegotiationResult,
    WearableOperationReceipt,
    WearableOperationRequest,
    WearablePermissionState,
    WearableRetention,
    WearableTransport,
    required_data_class,
    requires_visible_indicator,
)

__all__ = [
    "MAX_WEARABLE_DURATION_MS",
    "MAX_WEARABLE_EVENTS",
    "MAX_WEARABLE_PAYLOAD_BYTES",
    "WEARABLE_PROTOCOL_MAJOR",
    "WEARABLE_PROTOCOL_MINOR",
    "FakeWearableClient",
    "WearableAuthorization",
    "WearableCapability",
    "WearableCapabilityDescriptor",
    "WearableCapabilityLimits",
    "WearableClient",
    "WearableConnectionState",
    "WearableDataClass",
    "WearableDeviceDescriptor",
    "WearableError",
    "WearableFailureCode",
    "WearableNegotiationRequest",
    "WearableNegotiationResult",
    "WearableOperationReceipt",
    "WearableOperationRequest",
    "WearablePermissionState",
    "WearableRetention",
    "WearableTransport",
    "required_data_class",
    "requires_visible_indicator",
]
